apiVersion: v1
kind: Service
metadata:
  name: rollback-lab
  labels:
    app: rollback-lab
spec:
  selector:
    app: rollback-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
